class StripeServiceError(Exception): ...


class FailedToCreateProduct(StripeServiceError): ...


class FailedToCreatePrice(StripeServiceError): ...


class FailedToCreateSessions(StripeServiceError): ...


class FailedToGetStatus(StripeServiceError): ...
